name: Test Run with 2 stages

on:
    workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        if: always()
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: List directory contents of allure-results
        continue-on-error: true
        run: ls allure-results

      - name: Upload artifact
        continue-on-error: true
        uses: actions/upload-pages-artifact@v2
        with:
          name: allure-results
          path: allure-results
          
  generate-report:
  
    needs: run-tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Import artifacts from test run
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: 5

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
